### ISSUE TITLE
Pull-up or pull-down resistor?

### ISSUE THREAD

**Issue by adrcotfas** [mahfuz195/Pressure_sensor_BMP180#1]
In the schematic you have a pull-down resistor but in the code comments you have a pull-up resistor. Which one is correct?

**Comment by mahfuz195** [comment]
select line is pull down because of the mux. but sda and scl is pull up that is not showen in schematic.

Sent from Yahoo Mail on Android

**Comment by mahfuz195** [comment]
it should be pull up.may be the schematic is wrong.

Sent from Yahoo Mail on Android

**Comment by mahfuz195** [comment]
Issue solved.
